import = [
  "~/.config/alacritty/kanagawa_wave.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "DankMono Nerd Font"
size = 20
